### ISSUE TITLE
Add article for Geth -> Besu

### ISSUE THREAD

**Issue by frankisawesome** [etheralpha/clientdiversity-org#10]
I did a little write up a while ago on switching from Geth to Besu
https://medium.com/@frank_56417/switch-to-besu-as-el-client-for-your-rocketpool-minipool-node-de7d10e0ab86
Would be good to see it included as there's currently no article for Geth -> Besu!

**Comment by hanniabu** [comment]
Thanks @frankisawesome, I just added. Someone brought this question up, not sure if you know the answer:

> da3vr — 05/07/2022
Suggestion: Latest version of Besu (22.4.0) allows snap-sync and it's much quicker. No idea about RP setup and if that configuration is up to date.
I used this line in my startup script:
--sync-mode="X_SNAP" \

Link to comment in the EthStaker Discord: https://discord.com/channels/694822223575384095/933102729952395344/972692400843657278

**Comment by frankisawesome** [comment]
Seems like a question for someone from rocketpool :)
