### ISSUE TITLE
remove OpenEthereum

### ISSUE THREAD

**Issue by tvanepps** [etheralpha/clientdiversity-org#17]
is there a way to filter out OpenEthereum from the ethernodes data? similarly for the "Client Resources" section near the bottom. It's especially important in the lead up to the Merge that the community references up-to-date information

edit: [Officially deprecated](https://twitter.com/OpenEthereumOrg/status/1529147048758595585) now

**Comment by hanniabu** [comment]
@tvanepps when it's filtered out do you think it should be thrown into the "Others" column or have the count removed completely and the percents recalculated? The reason I've decided to leave it up to this point is that it still affects the current execution client distribution along with any of the other clients that miners are running while after the merge it would "resolve itself".

**Comment by tvanepps** [comment]
i think at a minimum, it should be removed from the "Execution clients" section completely, as it has been deprecated and won't be going through the Merge.

Moving it into "Others" on the Ethernodes crawler data seems like a good compromise, and hopefully the Merge takes care of them organically =)

**Comment by hanniabu** [comment]
This has been resolved here: https://github.com/etheralpha/clientdiversity-org/pull/20
