### ISSUE TITLE
Update link for Nimbus Concensus GitHub

### ISSUE THREAD

**Issue by AidanGG** [etheralpha/clientdiversity-org#27]
This link:

https://github.com/etheralpha/clientdiversity-org/blob/45d39c8e467a35c7cc216bcfc6055d67144c96f8/_data/clients-consensus.yml#L42

redirects to the nimbus-eth1 execution client, and should instead be changed to https://github.com/status-im/nimbus-eth2

**Comment by hanniabu** [comment]
Thanks for reaching out, just update! <https://github.com/etheralpha/clientdiversity-org/commit/3dedbb3015dd0f58f11364ef6c94de7452dccb35>
