### ISSUE TITLE
switch-to-lighthouse URL is not found

### ISSUE THREAD

**Issue by keivinonline** [etheralpha/clientdiversity-org#28]
Issue: https://lighthouse.sigmaprime.io/switch-to-lighthouse.html is no longer valid.

**Comment by hanniabu** [comment]
Thanks, I'll reach out to the team and see if there's an updated link

New URL: https://lighthouse-blog.sigmaprime.io/switch-to-lighthouse.html

**Comment by hanniabu** [comment]
Updated here: https://github.com/etheralpha/clientdiversity-org/commit/4f77c387e5a5b46206a120b9ad2ecd6f4043db80
